Popup Disappearing problem solved
jywarren/woofmark pull request #3
Opened 2020-06-08 16:34 UTC by NitinBhasneria

Fixes: #407
Presently the toolbar popup is not disappearing. After this fix, if we click anywhere else the popup will disappear.
![popup](https://user-images.githubusercontent.com/44112080/84056486-e85faf80-a9d3-11ea-92e8-3213c3727090.gif)
In this PR, a new crossvent function is added, this function will be called when we click anywhere except the popup box.

2020-06-08 16:35 UTC, NitinBhasneria commented
cc: @jywarren @emilyashley @VladimirMikulic @shreyaa-s @keshav234156 @Shulammite-Aso.

2020-06-08 18:42 UTC, VladimirMikulic commented on src/prompts/prompt.js
> +    console.log(str);
console logs shouldn't be present in the source code.

2020-06-08 18:43 UTC, VladimirMikulic commented on src/prompts/prompt.js
> +    if (!str.includes('wk-prompt')){
)_{ (_ -> space)

2020-06-08 18:43 UTC, VladimirMikulic requested changes
Please resolve minor issues.

2020-06-10 05:14 UTC, NitinBhasneria commented
We can also add a scroll event. By this when we scroll the page the popup will disappear, which in turn makes the user experience better.
@VladimirMikulic @shreyaa-s @keshav234156 @Shulammite-Aso @jywarren . What do you think?

2020-06-10 07:02 UTC, Shulammite-Aso commented
Yes @NitinBhasneria I think anything  that means focusing outside of the pop-up should make it disappear.

2020-06-10 10:56 UTC, VladimirMikulic commented
@NitinBhasneria maybe it's not a bad idea but it should trigger on a "bigger" scroll. Triggering popup removal on a slight scroll (a few pixels) which I sometimes accidentally do (others probably do as well) on my trackpad would be annoying to the users.

2020-06-10 10:58 UTC, VladimirMikulic commented on src/prompts/prompt.js
> +    var str = e.target.classList.value;
Please rename `str` to something meaningful. Comment above the function would also be appreciated.

2020-06-10 10:58 UTC, VladimirMikulic requested changes
One last change :)

2020-06-10 12:58 UTC, NitinBhasneria commented
Ok thanks for the idea @jywarren @VladimirMikulic

2020-06-14 15:41 UTC, NitinBhasneria commented
@VladimirMikulic @jywarren  Have a look now. 
I have added onscroll function which will make the popup disappear after more than 10 scrolls.
![popup](https://user-images.githubusercontent.com/44112080/84597737-a1663400-ae83-11ea-97ab-d11f9fd8e273.gif)

2020-06-23 19:54 UTC, jywarren commented
This looks really good! but @VladimirMikulic were you saying you think it may need to be on a scroll of more than X pixels, rather than a repeated scroll? 

Just to clarify before we get ready to merge this!

And, once we decide the exact behavior we want, @NitinBhasneria can you rename the title and first line of description above to clearly lay out the change in behavior? This will help us produce good documentation and track all the changes that go into each release.

Thank you!!! 🙌

2020-06-23 22:18 UTC, VladimirMikulic requested changes

2020-06-23 22:18 UTC, VladimirMikulic commented on src/prompts/prompt.js
> +    if (scrollSize>10) {
This should be formatted correctly.

2020-06-23 22:18 UTC, VladimirMikulic commented on src/prompts/prompt.js
> +    var classlist = e.target.classList.value;
`classlist` is too generic. Which element is this that we are referencing? Also, follow the camelCase naming convention.

2020-06-23 22:18 UTC, VladimirMikulic commented on src/prompts/prompt.js
> +  function rootClick (e) {
The function needs to be documented.

2020-06-23 22:18 UTC, VladimirMikulic commented
@jywarren Nitin covered the case I mentioned. :+1:

2020-06-24 18:40 UTC, jywarren commented
OK, great! Thanks, everyone! @NitinBhasneria once this is done could you open a PR to bump the version number on `woofmark` so that we can publish it and pull it into the editor repo? Thanks!!

2020-06-24 18:40 UTC, merged

2020-06-27 13:30 UTC, NitinBhasneria commented
> OK, great! Thanks, everyone! @NitinBhasneria once this is done could you open a PR to bump the version number on `woofmark` so that we can publish it and pull it into the editor repo? Thanks!!

created #6